<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="1" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="All Test Suite" duration-ms="10643" started-at="2021-11-10T21:39:39 GMT" finished-at="2021-11-10T21:39:50 GMT">
    <groups>
      <group name="Smoke">
        <method signature="LoginScenario.logintest(java.lang.String,java.lang.String)[pri:0, instance:TestSet1.LoginScenario@7f13d6e]" name="logintest" class="TestSet1.LoginScenario"/>
        <method signature="RegistrationScenario.loginTestcase1()[pri:1, instance:TestSet1.RegistrationScenario@7d0587f1]" name="loginTestcase1" class="TestSet1.RegistrationScenario"/>
      </group> <!-- Smoke -->
    </groups>
    <test name="C:/Users/kalya/Downloads/test.project/EndtoEndProject/src/test/java/TestSet1" duration-ms="10643" started-at="2021-11-10T21:39:39 GMT" finished-at="2021-11-10T21:39:50 GMT">
      <class name="TestSet1.LoginScenario">
        <test-method status="PASS" signature="objectRepo(org.testng.ITestContext)[pri:0, instance:TestSet1.LoginScenario@7f13d6e]" name="objectRepo" is-config="true" duration-ms="2163" started-at="2021-11-10T21:39:45 GMT" finished-at="2021-11-10T21:39:48 GMT">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@4ef27d66]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- objectRepo -->
        <test-method status="FAIL" signature="logintest(java.lang.String,java.lang.String)[pri:0, instance:TestSet1.LoginScenario@7f13d6e]" name="logintest" duration-ms="1756" started-at="2021-11-10T21:39:48 GMT" data-provider="dataprover2" finished-at="2021-11-10T21:39:49 GMT">
          <params>
            <param index="0">
              <value>
                <![CDATA[kalyan2342342]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at TestSet1.LoginScenario.logintest(LoginScenario.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
      </class> <!-- TestSet1.LoginScenario -->
      <class name="TestSet1.RegistrationScenario">
        <test-method status="PASS" signature="initializewebdriver(java.lang.String)[pri:0, instance:TestSet1.RegistrationScenario@7d0587f1]" name="initializewebdriver" is-config="true" duration-ms="8390" started-at="2021-11-10T21:39:31 GMT" finished-at="2021-11-10T21:39:39 GMT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializewebdriver -->
        <test-method status="PASS" signature="objectRepo(org.testng.ITestContext)[pri:0, instance:TestSet1.RegistrationScenario@7d0587f1]" name="objectRepo" is-config="true" duration-ms="2970" started-at="2021-11-10T21:39:39 GMT" finished-at="2021-11-10T21:39:42 GMT">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@4ef27d66]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- objectRepo -->
        <test-method status="PASS" signature="loginTestcase1()[pri:1, instance:TestSet1.RegistrationScenario@7d0587f1]" name="loginTestcase1" duration-ms="1353" started-at="2021-11-10T21:39:42 GMT" finished-at="2021-11-10T21:39:43 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestcase1 -->
        <test-method status="FAIL" signature="confirmerrors()[pri:2, instance:TestSet1.RegistrationScenario@7d0587f1]" name="confirmerrors" duration-ms="115" started-at="2021-11-10T21:39:43 GMT" finished-at="2021-11-10T21:39:43 GMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Email is required] but found [Email is required.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Email is required] but found [Email is required.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestSet1.RegistrationScenario.confirmerrors(RegistrationScenario.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirmerrors -->
        <test-method status="PASS" signature="GobackHomepage()[pri:0, instance:TestSet1.RegistrationScenario@7d0587f1]" name="GobackHomepage" is-config="true" duration-ms="1581" started-at="2021-11-10T21:39:44 GMT" finished-at="2021-11-10T21:39:45 GMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GobackHomepage -->
      </class> <!-- TestSet1.RegistrationScenario -->
    </test> <!-- C:/Users/kalya/Downloads/test.project/EndtoEndProject/src/test/java/TestSet1 -->
  </suite> <!-- All Test Suite -->
</testng-results>
